function buildTOC(planText: string): string {
  const lines = planText.split('\n');
  const toc: { num: string; title: string }[] = [];
  for (const line of lines) {
    const match = line.match(/^##\s+(\d+)\.\s+(.+)/);
    if (match) {
      toc.push({ num: match[1], title: match[2] });
    }
  }
  if (toc.length === 0) return '';
  return toc.map(s => `<li style="margin: 4px 0;"><a href="#section-${s.num}" style="color: #2563eb; text-decoration: none;">${s.num}. ${s.title}</a></li>`).join('');
}

function planToHTML(planText: string, title: string): string {
  const toc = buildTOC(planText);

  let inTable = false;
  let tableRows: string[] = [];
  const lines = planText
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .split('\n');

  const flushTable = () => {
    if (tableRows.length < 2) { tableRows = []; return ''; }
    const headerCells = tableRows[0].split('|').filter(c => c.trim());
    const bodyRows = tableRows.slice(1);
    let html = '<table style="width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 10pt;">';
    html += '<thead><tr>';
    headerCells.forEach(cell => {
      html += `<th style="background: #f1f5f9; border: 1px solid #cbd5e1; padding: 10px 12px; text-align: left; font-weight: 600; color: #1e293b;">${cell.trim()}</th>`;
    });
    html += '</tr></thead><tbody>';
    bodyRows.forEach(row => {
      const cells = row.split('|').filter(c => c.trim());
      if (cells.length > 0) {
        html += '<tr>';
        cells.forEach(cell => {
          html += `<td style="border: 1px solid #cbd5e1; padding: 8px 12px; color: #475569;">${cell.trim()}</td>`;
        });
        html += '</tr>';
      }
    });
    html += '</tbody></table>';
    tableRows = [];
    return html;
  };

  let bodyLines: string[] = [];
  for (const line of lines) {
    if (/^\|.+\|$/.test(line.trim()) && !line.includes('---')) {
      if (!inTable) { inTable = true; }
      tableRows.push(line);
      continue;
    }
    if (inTable && /^\|.+\|$/.test(line.trim()) === false) {
      bodyLines.push(flushTable());
      inTable = false;
    }
    if (inTable && line.includes('---')) {
      continue;
    }
    if (inTable) {
      continue;
    }

    if (/^##\s+\d+\.\s/.test(line)) {
      const sectionNum = line.match(/^##\s+(\d+)\./)?.[1] || '';
      const sectionTitle = line.replace(/^##\s+\d+\.\s+/, '');
      bodyLines.push(`<h2 id="section-${sectionNum}" style="color: #1e293b; border-bottom: 2px solid #2563eb; padding-bottom: 8px; margin-top: 32px;">${sectionNum}. ${sectionTitle}</h2>`);
    } else if (/^###\s/.test(line)) {
      bodyLines.push(`<h3 style="color: #334155; margin-top: 20px;">${line.replace(/^###\s+/, '')}</h3>`);
    } else if (/^\*\*(.+)\*\*$/.test(line.trim())) {
      bodyLines.push(`<h3 style="color: #334155; margin-top: 20px;">${line.replace(/\*\*/g, '')}</h3>`);
    } else if (/^- /.test(line) || /^\* /.test(line)) {
      bodyLines.push(`<li style="margin: 4px 0 4px 20px; color: #475569;">${line.replace(/^[-*]\s+/, '')}</li>`);
    } else if (line.trim() === '') {
      bodyLines.push('');
    } else {
      bodyLines.push(`<p style="color: #475569; line-height: 1.7; margin: 8px 0;">${line}</p>`);
    }
  }
  if (inTable) bodyLines.push(flushTable());

  let body = bodyLines.join('\n');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    @page { margin: 2.54cm; }
    body { font-family: 'Calibri', 'Arial', sans-serif; font-size: 11pt; color: #1e293b; line-height: 1.6; max-width: 210mm; margin: 0 auto; padding: 20px; }
    h1 { font-size: 24pt; color: #1e293b; border-bottom: 3px solid #2563eb; padding-bottom: 12px; margin-bottom: 24px; }
    h2 { font-size: 16pt; color: #1e293b; border-bottom: 2px solid #2563eb; padding-bottom: 8px; margin-top: 32px; }
    h3 { font-size: 13pt; color: #334155; margin-top: 20px; }
    p { color: #475569; line-height: 1.7; margin: 8px 0; }
    li { margin: 4px 0 4px 20px; color: #475569; }
    ul { padding-left: 20px; }
    .toc { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px 28px; margin: 20px 0 32px 0; }
    .toc h2 { border: none; margin-top: 0; font-size: 14pt; }
    .toc ul { list-style: none; padding: 0; }
    .header { text-align: center; margin-bottom: 40px; }
    .header h1 { border: none; margin-bottom: 4px; }
    .header p { color: #64748b; font-size: 10pt; margin: 0; }
    .page-break { page-break-before: always; }
    @media print { body { padding: 0; } }
    .footer-note { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 9pt; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <p>Generated by Investours AI Business Plan Generator</p>
  </div>

  ${toc ? `<div class="toc"><h2>Table of Contents</h2><ul>${toc}</ul></div><div class="page-break"></div>` : ''}

  ${body}

  <div class="footer-note">
    <p>This business plan was generated by Investours AI. Review and customize before submission.</p>
    <p>Page 1</p>
  </div>

  <script>
    const pageNum = document.querySelector('.footer-note p:last-child');
    let page = 1;
    const printCallback = function() { pageNum.textContent = 'Page ' + page; page++; };
    if (window.matchMedia) {
      const mediaQueryList = window.matchMedia('print');
      mediaQueryList.addListener(function(mql) { if (mql.matches) printCallback(); });
    }
  </script>
</body>
</html>`;
}

export function downloadDOCX(planText: string, businessName: string) {
  const name = businessName?.trim() || 'Business Plan';
  const title = `${name} - Business Plan`;
  const html = planToHTML(planText, title);
  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${name.replace(/\s+/g, '_')}_Business_Plan.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadPDF(planText: string, businessName: string) {
  const name = businessName?.trim() || 'Business Plan';
  const title = `${name} - Business Plan`;
  const html = planToHTML(planText, title);

  const win = window.open('', '_blank');
  if (!win) {
    alert('Please allow popups to download PDF');
    return;
  }
  win.document.write(html);
  win.document.close();
  win.focus();

  setTimeout(() => {
    win.print();
  }, 500);
}
